bad_relations =["sitting on horse's back",
"under child's feet",
"standing on surfboard",
"touching trunks",
"Opposite sides of image",
"on the surface of bus",
"interacting physically",
"child holds",
"separate individuals",
"Parallel and separate",
"left, right",
"child holds","on sink",
"on man's neck",
"to left/right of",
"Opposite corners of room",
"below couple",
"holding the bicycle", 
"separate entities",
"inside tv",
"Attached to vehicle, above",
    "near horse in trailer",
    "printed on stop sign",
    "on plate",
    "boy holds",
    "to right of plate",
    "beside bowl",
    "Separated by space",
    "uses with hands",
    "Above and adjacent to stove",
    "underneath the feet",
    "outside bowl",
    "and separate",
    "bowl is in front of the picture",
    "under 's feet",
    "same carrot",
    "being held by hand",
    "No relationship",
    "",
    "carries people on its back",
    "standing near baseball glove",
    "on shelf behind",
    "child sitting on woman's lap",
    "person holding kite's string",
    "in touches in",
    "on table near",
    "near 's mouth",
    "couches separate and not adjacent",
    "touching noses",
    "Attached to 's feet",
    "gloves are behind the person",
    "umpire behind catcher",
    "cuts fish, not",
    "behind computer",
    "around neck",
    "person behind baseball bat",
    "teddy bear is above cat",
    "above, below",
    "vase is in front of chair",
    "cell phone is below bottle",
    "on plate, plate on",
    "dining table is behind fire hydrant ",
    "above pedestrian",
    "Inside and outside",
    "man stands beside",
    "shades",
    "on cutting board, knife nearby",
    "on top of cutting board",
    "book is below toilet",
    "sitting near handbag",
    "apple is in front of handbag",
    "person is below clock ",
    "on bus, near",
    "car is in front of motorcycle",
    "banana is behind motorcycle",
    "on 's shoulder",
    "on 's neck",
    "opposite corners of same",
"sitting on horse's back",
    "under child's feet",
    "standing on surfboard",
    "touching trunks",
    "on the surface of bus",
    "opposite sides of image",
    "near 's waist",
    "interacting physically",
"left, right",
    "separate individuals",
  "child holds",
    "on sink",
    "on man's neck",
    "to left/right of",  
 "below couple",
 "holding the bicycle",
    "separate entities",
    "inside tv",
    "attached to vehicle, above",
    "near horse in trailer",
    "printed on stop sign",
    "on screen",
    "holds string",
    "on plate",
    "boy holds",
    "adjacent, touching edges",
    "above 's head",
    "to right of plate",
    "beside bowl",
    "separated by space",
    "uses with hands",
    "above on plate",
    "above and adjacent to stove",
    "underneath the feet",
    "outside bowl",
    "bowl is in front of the picture",
    "under 's feet",
    "same carrot",
    "being held by hand",
    "no relationship",
    "behind people",
    "in behind kite",
    "",
    "held near ear",
    "near 's hand",
    "carries people on its back",
    "adjacent, slightly to right",
    "opposite sides of each other",
    "standing near baseball glove",
    "on shelf behind",
    "child sitting on woman's lap",
    "person holding kite's string",
    "on table near",
    "near 's mouth",
    "couches separate and not adjacent",
    "touching noses",
    "inside, outside",
    "in air",
    "on 's hand",
"attached to 's feet",
    "gloves are behind the person",
    "umpire behind catcher",
    "cuts fish, not",
    "behind computer",
    "around neck",
    "around 's neck",
    "and contain side by side",
    "person behind baseball bat",
    "teddy bear is above cat",
    "above, below",
    "vase is in front of chair",
    "cell phone is below bottle",
    "on plate, plate on",
    "dining table is behind fire hydrant",
    "above pedestrian",
    "inside and outside",
    "man stands beside",
    "on cutting board, knife nearby",
    "on top of cutting board",
    "book is below toilet",
    "sitting near handbag",
    "apple is in front of handbag",
    "person is below clock",
    "on bus, near",
    "car is in front of motorcycle",
    "banana is behind motorcycle",
    "on 's shoulder",
    "on 's neck",
    "parallel, separated by a table",
    "suitcase is under backpack",
    "on plate, not in",
    "baseball is in the air",
    "person is under surfboard",
    "reading the book",
    "person is holding the string",
    "near , close proximity",
    "knives side by side",
    "hand holds",
    "opposite sides of screen",
    "not near",
    "holding the suitcase",
    "person is holding the chair",
    "on door",
    "bus is behind the car",
    "over shoulder",
    "separate and apart",
    "carries on back",
    "two individuals in close proximity",
    "held by 's hand",
    "above pizza slice",
    "on plate, near",
    "holds food above",
    "near , brushing teeth",
    "toothbrush is inside person's mouth",
    "carrot is in the bowl",
    "overlap slightly",
    "on right of bread",
    "above salad",
    "suitcase is under person",
    "tv is in front of bed",
    "in farther away from one in",
    "on boat, on land",
    "above on shelf",
    "in child's mouth",
    "below plate",
    "sandwiches identical",
    "opposite corners of image",
    "opposite",
    "in water",
    "shows on screen",
    "in closer",
    "separated by distance",
    "opposite sides",
    "spoon is inside the bowl",
    "man in observing in",
    "on plate, which on",
    "orange is below the bowl",
    "separate",
    "not physically present",
    "chid is eating the apple",
    "in in child's hand",
    "parallel to right of plate",
    "slice inside",
    "car is behind bottle",
    "above catcher's head",
    "on sidewalk, across street",
    "backpack is under the banana",
    "adjacent to pears",
    "on 's lap",
    "above on wall",
"person is behind cell phone",
"car is behind the fire hydrant"
"inside , adjacent to spoon",
"above plate",
"hot dogs are being made",
"standing outside the bus",
"above on table",
    "holds in hand",
    "on hand",
    "holds above tray",
    "in kicking ball toward in",
    "bench is behind the person",
    "holds bat, near",
    "boy below",
    "on floor, on couch",
    "person is sitting on cow's back",
    "on person's wrist",
    "cat is on the bed",
    "in person's hand",
    "benches parallel and separated by bleachers",
    "signs stacked vertically",
    "reflection in mirror",
    "on plate, adjacent to fork",
    "cup is on the plate",
    "throwing ball to",
    "on top of tray, next to food",
"adjacent to itself",
    "under 's foot",
    "no physical relationship",
    "symmetrical",
    "on man's neck",
    "touches 's neck",
    "on near vase",
    "on 's neck",
    "near 's hand",
    "man stands to left of",
    "",
"under 's feet",
    "on plate",
    "not near",
"holding on lap",
"sandwiches adjacent",
    "contains grapes, not",
    "on 's back",
    "to right of laptop",
    "'s feet above",
    "controls from distance",
    "and separate",
    "holding in hand",
    "not physically related to",
    "holds near control panel",
    "above, below",
    "on bicycle near",
    "above 's head",
    "catcher behind umpire",
    "on plate, which on",
    "adjacent, touching feet",
    "benches parallel",
    "not related to spatially",
    "opposite directions",
    "opposite corners of same",
    "child in inside in",
    "opposite sides of screen",
    "separate entities",
"above on surface",
    "carries the dog",
    "parallel, crossing paths",
    "knives overlapping",
"opposite corners of same square",
"opposite corners of a square",
"on hand",
"chef near",
    "opposite sides of same",
"behind people",
"near man's feet",
    "two individuals not physically connected",
"on tray, tray on",
"on phone, near",
    "near 's ear",
    "knives parallel and equidistant",
    "opposite sides of image",
      "in air",
      "near 's shoulder",
    "outside, inside",
    "child to left of",
    "above 's hand",
     "opposite corners",
     "opposite sides of court",
     "in 's hand",
     "behind , in front of",
     "car is behind the fire hydrant",
     "inside , adjacent to spoon",
     "behind batter, facing forward",
     "baby held by woman",
     "on top of tray, on",
     "in mouth",
     "hand touching slice",
     "holds near their mouth",
      "baseball bat is near person's feet",
    "opposite corners of room",
    "opposite to each ther",
]

adjecent=["adjacent","side by side, parallel alignment",
"side by side, facing opposite directions",
"signs adjacent to each other",
    "opposite sides of",
"adjacent, overlapping hair strands",
"adjacent , not touching",
"adjacent, touching, side-by-side",
"side by side, overlapping slightly",
"side by side, adjacent",
"balls adjacent",
    "overlap spatially",
    "plants adjacent",
"parallel and separate",
    "phones side-by-side",
    "adjacent, touching edges",
"in adjacent to in",
"buses side by side",
"parallel, side-by-side tracks",
"adjacent to each other",
"parallel, side-by-side tracks",
"adjacent to",
    "plants side by side",
    "parallel, side-by-side",
"signs adjacent",
"and adjacent",
"adjacent, interacting, close proximity",
    "adjacent, side-by-side",
    "adjacent, close proximity", "adjacent, overlapping, side-by-side",
"adjacent to pears","adjacent on same surface",
    "adjacent, side-by-side placement",
"side by side, facing each other",
"tables parallel",
    "black adjacent",
    "buses adjacent",
    "tables adjacent",
    "parallel and adjacent",
    "benches parallel and adjacent",
    "parallel tracks, adjacent",
    "side by side, adjacent",
    "adjacent to",
"and adjacent",
"plants adjacent",
    "adjacent, side by side",
    "adjacent, side-by-side",
    "couches adjacent",
    "adjacent, overlapping, close proximity",
    "adjacent, overlapping",
    "adjacent to each other",
    "knives parallel and adjacent",
    "adjacent, touching edges",
    "side by side, adjacent",
    "parallel tracks, adjacent",
    "parallel, side by side",
    "parallel, side-by-side",
    "side by side, parallel placement",
    "man and adjacent",
    "adjacent, slightly to right",
    "parallel and adjacent",
    "benches parallel and adjacent",
    "adjacent, not touching",
    "adjacent, overlapping, or touching",
    "in adjacent to in",
    "tables adjacent",
    "buses adjacent",
    "and adjacent",
    "plants adjacent",
    "man and adjacent",
    "adjacent, not touching",
    "adjacent, overlapping, or touching",
    "in adjacent to in",
    "adjacent,touching",
    "adjacent , side by side",
    "adjacent, touching, close proximity",
    "mice side by side",
    "and side by side",
    "adjacent , separate",
   
    ]

change={"facing each other across water":"facing across water",
    "in to right of in":'to right of',
    "holds vertically":'holding',
    "in standing behind in":'standing behind',
    "in sitting at in":'sitting at',
    "on , riding wave":'on',
    "in below in":'below',
"in behind":'behind',
    "inside, within, contained by":'inside',
"above, on top of":'above',
    "overlap each other":'overlapping',
    "opposite sides of room":'opposite sides of room',
"opposite sides of road":'opposite side of road',
    "in sitting on":'sitting on',
    "close proximity, overlapping":'overlapping',
"opposite to each other":'opposite',
"inside of other":'inside of',
    "i front of":'in front of',
    "near , slightly distant":'next to',
    "behind people":'behind',
"in behind kite":'behind',
"in near in":'next to',
"gloves side by side":'next to',
"bats side by side":'next to',
"side by side, riding together":'next to',
"side by side, horizontally aligned":'next to',
"and contain side by side":'next to',
"above, distant, not interacting":'above',
"in standing in front of in":'standing in front of',
"near , interacting with it":'next to',
"in above in":'above',
"in holding in":'holding',
"on 's back":'on back',
"in behind in":'behind',
"parallel and separate":'parallel',
"parallel, side by side":'next to',
"parallel, side-by-side":'next to',
"in near in":'next to',
"in touches in":'touches',
"behind , separated by window":'behind',
"gloves side by side":'next to',
"bats side by side":'next to',
"in facing in":'facing in',
"above, distant, not interacting":'above',
"in standing in front of in":'standing in front of',
"adjacent, overlapping slightly":'next to',
"parallel, not touching":'parallel',
"close proximity, interacting":'next to',
"above, in sky":'above',
"in to left of in":'to left of',
"facing each other, close proximity":"facing each other",
"overhead, parallel, above-ground":'overhead',
"glasses side by side": 'next to',
"two people side by side": 'next to',
"balls adjacent": 'next to',
"side-by-side": 'next to',
"parallel and side-by-side": 'next to',
"near , not touching": 'next to',
"inside , and inside": 'inside',
"phones side by side": 'next to',
"sandwiches side by side": 'next to',
"meters side by side": 'next to',
"bats parallel and adjacent": 'next to',
"in taking a picture of in":'taking a picture of',
"glasses side by side": 'next to',
"side by side, close proximity": 'next to',
"in on top of in":'on top of',
"in to left of in":'to left of',
"inside of each other":'inside of',
"sits near, not directly on,":'sits near',
"in larger":'larger',
 "in in front of in":'in front of',
"above, higher altitude":'above',
"and in same vehicle":'in same vehicle',
"above one":'above',
"in next to in":'next to',
"above, in same room":'above',
"in standing next to in":'standing next to',
"above , cutting it":'above, cutting',
"inside , and inside":'inside',
"in , which inside":'inside',
"in above in":'above',
'next to each other':'next to',
'side byside':'next to',
"parallel on separate tracks":'parallel to',
"parallel and opposite":'next to',
"inside , adjacent to spoon":'inside adjacent to spoon',
"signs side by side":'next to',
"identical in design":'looks similar to',
"side by side":'next to',
"identical twins":'looks similar to',
"behind, partially obscured":'behind',
"opposite each other":'opposite to',
"above, cutting":"cutting",
"being held by":'held by',
"opposite each other":'opposite to',
"ridden":'ridden by'
}

composition_relations=["standing on", "lying on","contains",
    "wearing","holding","sitting on",
    "seated at",
    "riding", "carrying","held by",
    "consists of","wears","worn by","attached to","ridden"]

